Traceback (most recent call last):
<<<<<<< HEAD
  File "handlingErrors.py", line 12, in makeBox
    raise Exception('Errored')
Exception: Errored

Traceback (most recent call last):
  File "handlingErrors.py", line 12, in makeBox
    raise Exception('Errored')
Exception: Errored

Traceback (most recent call last):
  File "handlingErrors.py", line 12, in makeBox
    raise Exception('Errored')
Exception: Errored

Traceback (most recent call last):
  File "handlingErrors.py", line 12, in makeBox
    raise Exception('Symbol character exceeds length requirement')
Exception: Symbol character exceeds length requirement

Traceback (most recent call last):
  File "handlingErrors.py", line 12, in makeBox
    raise Exception('Symbol character exceeds length requirement')
Exception: Symbol character exceeds length requirement

Traceback (most recent call last):
  File "handlingErrors.py", line 12, in makeBox
    raise Exception('Symbol character exceeds length requirement')
Exception: Symbol character exceeds length requirement

Traceback (most recent call last):
  File "handlingErrors.py", line 12, in makeBox
    raise Exception('Symbol character exceeds length requirement')
Exception: Symbol character exceeds length requirement

Traceback (most recent call last):
  File "handlingErrors.py", line 12, in makeBox
    raise Exception('Symbol character exceeds length requirement')
Exception: Symbol character exceeds length requirement

Traceback (most recent call last):
  File "handlingErrors.py", line 12, in makeBox
    raise Exception('Symbol character exceeds length requirement')
Exception: Symbol character exceeds length requirement

Traceback (most recent call last):
  File "handlingErrors.py", line 12, in makeBox
    raise Exception('Symbol character exceeds length requirement')
Exception: Symbol character exceeds length requirement
=======
  File "workingwitherrors.py", line 30, in <module>
    raise Exception('This is the error message')
Exception: This is the error message

Traceback (most recent call last):
  File "workingwitherrors.py", line 30, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
>>>>>>> 2e9c96fc28eac6ae796d15be48a1a04bce7f3103

